#!/usr/bin/env bash
# _arms/verify-portal.sh — verify / heal the mirror portal + regenerate INDEX.md
#
# Root-to-leaves durability: the 8 mirror links are chezmoi-tracked source
# (symlink_<name>.tmpl, templated on {{ .chezmoi.homeDir }}). chezmoi is the
# source of truth and the restore mechanism — this script wraps it.
#
#   ./verify-portal.sh          # heal from tracked source, check targets, regen INDEX.md
#   ./verify-portal.sh --check  # check only, no mutation; exit 1 if any link MISSING or DANGLING
#   ./verify-portal.sh --heal   # alias for default (explicit)
#
# Restore from scratch (e.g. fresh machine): `chezmoi apply --force ~/_arms/mirror`
# regenerates every link. This script is the health-check + INDEX layer on top.
#
# Exit 0 = every expected link present AND resolving. Exit 1 = missing or dangling.

set -euo pipefail
ARMS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIRROR="$ARMS/mirror"
MODE="heal"
[ "${1:-}" = "--check" ] && MODE="check"

# Expected link set = what chezmoi declares as source-of-truth (authoritative),
# falling back to whatever links are currently present if chezmoi is unavailable.
expected=""
if command -v chezmoi >/dev/null 2>&1; then
  expected="$(chezmoi managed 2>/dev/null | /usr/bin/grep '_arms/mirror/' | /usr/bin/sed 's#.*_arms/mirror/##' || true)"
fi
if [ -z "$expected" ]; then
  expected="$(cd "$MIRROR" && for l in *; do [ -L "$l" ] && echo "$l"; done)"
  echo "note: chezmoi unavailable — checking only present links, cannot detect missing ones" >&2
fi

# Heal mode: reconcile live links to tracked source before checking.
if [ "$MODE" = "heal" ] && command -v chezmoi >/dev/null 2>&1; then
  chezmoi apply --force "$MIRROR" 2>/dev/null || true
fi

missing=0; dangling=0; ok=0; rows=""
for name in $expected; do
  link="$MIRROR/$name"
  if [ ! -L "$link" ]; then
    rows="${rows}| \`mirror/${name}\` | — | — | **MISSING** |"$'\n'
    echo "MISSING: mirror/${name} (declared in chezmoi, absent on disk)" >&2
    missing=$((missing + 1)); continue
  fi
  target="$(readlink "$link")"
  if [ -e "$link" ]; then
    if [ -d "$link/" ]; then n="$(/bin/ls "$link/" 2>/dev/null | /usr/bin/wc -l | /usr/bin/tr -d ' ')"; else n="file"; fi
    rows="${rows}| \`mirror/${name}\` | \`${target}\` | ${n} | ok |"$'\n'
    ok=$((ok + 1))
  else
    rows="${rows}| \`mirror/${name}\` | \`${target}\` | — | **DANGLING** |"$'\n'
    echo "DANGLING: mirror/${name} -> ${target} (target moved)" >&2
    dangling=$((dangling + 1))
  fi
done

own="$(/bin/ls "$ARMS/skills" 2>/dev/null | /usr/bin/wc -l | /usr/bin/tr -d ' ')"

if [ "$MODE" = "heal" ]; then
  {
    echo "# \`_arms/\` — portal index (live snapshot)"
    echo
    echo "**Regenerated by \`verify-portal.sh\`.** The chezmoi-tracked \`symlink_*.tmpl\` source is authoritative; this is a snapshot. Restore all links anywhere with \`chezmoi apply --force ~/_arms/mirror\`."
    echo
    echo "## Zone 1 — our work"
    echo "| Path | Skills |"; echo "|---|---|"
    echo "| \`skills/\` (operator-authored) | ${own} |"
    echo
    echo "## Zone 2 — the mirror portal"
    echo "| Link | Reflects | Entries | Status |"; echo "|---|---|---|---|"
    printf "%s" "$rows"
    echo
    echo "## Verify / heal / regen"
    echo '```sh'
    echo "cd $ARMS && ./verify-portal.sh        # heal + regen"
    echo "./verify-portal.sh --check            # check only (CI / hook)"
    echo "chezmoi apply --force ~/_arms/mirror  # restore from tracked source"
    echo '```'
  } > "$ARMS/INDEX.md"
  echo "INDEX.md regenerated (${own} own skills; ${ok} ok, ${missing} missing, ${dangling} dangling)."
fi

if [ "$missing" -gt 0 ] || [ "$dangling" -gt 0 ]; then
  echo "FAIL: ${missing} missing, ${dangling} dangling. Heal: chezmoi apply --force ~/_arms/mirror (missing) · ln -sfn <new-target> mirror/<name> + chezmoi add (moved target)." >&2
  exit 1
fi
echo "OK: all ${ok} expected mirror links present and resolving."
