#!/usr/bin/env python3
"""Rebuild the synthetic Artifact 001 family, never an archival artwork.

Run inside this incubator. All generated bytes stay in artifact-001/.
Media can be generated on any FFmpeg toolchain; exact source bytes are identified
by the resulting hashes, not promised to match across encoder versions.
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from pathlib import Path
from composition import ENGINE_VERSION, RNG, SCHEMA_VERSION, save_state, sha256_file, from_authoring_model

HERE = Path(__file__).resolve().parent

def write_json(path: Path, obj: object) -> None:
    path.write_text(json.dumps(obj, indent=2) + '\n', encoding='utf-8')

def prepare(root: Path) -> list[Path]:
    root.mkdir(parents=True, exist_ok=True)
    for child in ('media', 'evidence', 'renders'):
        (root / child).mkdir(exist_ok=True)
    commands = []
    sources = []
    for i in range(6):
        file = root / 'media' / f'loop-{i+1}.mp4'
        command = ['ffmpeg','-hide_banner','-loglevel','error','-y','-filter_threads','1',
                   '-f','lavfi','-i','testsrc2=s=320x320:r=24:d=3',
                   '-f','lavfi','-i',f'sine=frequency={220+i*110}:sample_rate=48000:duration=3',
                   '-vf',f'hue=h={i*57},'+('hflip' if i%2 else 'vflip'),
                   '-c:v','libx264','-preset','ultrafast','-crf','20','-threads','1','-pix_fmt','yuv420p',
                   '-c:a','aac','-shortest',str(file.relative_to(HERE))]
        # Reuse the evidenced source bytes when present, then hash them afresh.
        if not file.exists():
            subprocess.run(command, cwd=HERE, check=True)
        commands.append(command)
        sources.append(dict(id=f'media-{i+1}', path=f'media/loop-{i+1}.mp4',
                            sha256=sha256_file(file),kind='video',duration='3'))
    still = root / 'media' / 'still.png'
    command = ['ffmpeg','-hide_banner','-loglevel','error','-y','-i',str(root/'media/loop-1.mp4'),
               '-frames:v','1',str(still)]
    if not still.exists():
        subprocess.run(command, cwd=HERE, check=True)
    commands.append(command)
    still_src = dict(id='still',path='media/still.png',sha256=sha256_file(still),kind='still',duration='2')
    write_json(root/'evidence/source-commands.json',commands)
    write_json(root/'sources.json',dict(kind='synthetic-engineering-media',sources=sources+[still_src]))
    from artifact001_layouts import build_artifact001
    paths = []
    for count in (3,4,5,6):
        authoring = build_artifact001(count)
        source_map = {f'fixtures/loop-{i+1}.mp4': sources[i] for i in range(count)}
        state = from_authoring_model(authoring, source_map)
        write_json(root/f'authoring-{count}.json', authoring.to_dict())
        path = root/f'state-{count}.json'
        save_state(state,path)
        paths.append(path)
    # A separate compatibility/control proof: still duration and all four controls.
    state = json.loads(paths[0].read_text())
    state['sources'] = sources[:3]+[still_src]
    state['allow_source_reuse'] = True  # explicit bank overlap in this control fixture only
    state['loops'][0]['bank'] = ['still']
    state['loops'][1]['bank'] = ['media-2','media-3']
    state['events'] = [dict(op='hold',frame=24,loop='loop-2',value=True),
                       dict(op='hold',frame=48,loop='loop-2',value=False),
                       dict(op='reroll',frame=60,loop='loop-2'),
                       dict(op='swap',frame=84,a='loop-2',b='loop-3'),
                       dict(op='move',frame=108,loop='loop-1',orientation='portrait',
                            rect=['1/10','3/100','4/5','21/50'])]
    save_state(state,root/'state-still-controls.json')
    return paths+[root/'state-still-controls.json']

def probe(path: Path) -> dict:
    result=subprocess.run(['ffprobe','-v','error','-show_entries',
                           'format=duration,size:stream=codec_name,codec_type,width,height,r_frame_rate,nb_frames',
                           '-of','json',str(path)],check=True,capture_output=True,text=True)
    return json.loads(result.stdout)

def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--prepare-only',action='store_true')
    parser.add_argument('--draft',action='store_true',help='360x640/640x360, not the full reference matrix')
    args=parser.parse_args()
    root=HERE/'artifact-001'
    states=prepare(root)
    if args.prepare_only:
        return
    receipts=[]
    for state in states:
        orientations=('portrait',) if 'still-controls' in state.stem else ('portrait','landscape')
        for orientation in orientations:
            name=f'{state.stem}-{orientation}'+('-draft' if args.draft else '')
            target=root/'renders'/f'{name}.mp4'
            command=[sys.executable,'render_triptych.py','--state',str(state.relative_to(HERE)),
                     '--orientation',orientation,'--output',str(target.relative_to(HERE)),
                     '--preset','ultrafast','--crf','20']
            if args.draft:
                size=(360,640) if orientation=='portrait' else (640,360)
                command+=['--width',str(size[0]),'--height',str(size[1])]
            log=root/'evidence'/f'{name}.log'
            with log.open('w') as stream:
                result=subprocess.run(command,cwd=HERE,stdout=stream,stderr=subprocess.STDOUT)
            if result.returncode:
                raise SystemExit(f'Render failed ({result.returncode}); inspect {log}')
            still=target.with_suffix('.png')
            still_command=['ffmpeg','-hide_banner','-loglevel','error','-y','-ss','2',
                           '-i',str(target),'-frames:v','1',str(still)]
            subprocess.run(still_command,check=True)
            receipts.append(dict(command=command,returncode=0,output=str(target.relative_to(root)),
                                 sha256=sha256_file(target),facts=probe(target),
                                 still=str(still.relative_to(root)),still_sha256=sha256_file(still)))
            write_json(root/'evidence'/('draft-renders.json' if args.draft else 'renders.json'),receipts)
            print(f'RENDERED {name}',flush=True)

if __name__=='__main__':
    main()
